"""make league_sessions.session_id nullable and drop FK to sessions

Revision ID: 44b1c5fd00c4
Revises: 48b042aef178
Create Date: 2026-03-09 00:16:25.993397

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '44b1c5fd00c4'
down_revision: Union[str, None] = '48b042aef178'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('league_sessions', 'session_id',
               existing_type=sa.UUID(),
               nullable=True)
    op.drop_constraint(op.f('league_sessions_session_id_fkey'), 'league_sessions', type_='foreignkey')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key(op.f('league_sessions_session_id_fkey'), 'league_sessions', 'sessions', ['session_id'], ['id'])
    op.alter_column('league_sessions', 'session_id',
               existing_type=sa.UUID(),
               nullable=False)
    # ### end Alembic commands ###
