"""add league models

Revision ID: 48b042aef178
Revises: 576ecf635f11
Create Date: 2026-03-09 00:10:00.295698

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '48b042aef178'
down_revision: Union[str, None] = '576ecf635f11'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('league_teams',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('code', sa.String(length=10), nullable=False),
    sa.Column('created_by', sa.UUID(), nullable=True),
    sa.Column('total_points', sa.Float(), server_default='0', nullable=False),
    sa.Column('total_sessions', sa.Integer(), server_default='0', nullable=False),
    sa.Column('member_count', sa.Integer(), server_default='0', nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('code')
    )
    op.create_table('league_players',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('nickname', sa.String(length=20), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=True),
    sa.Column('password_hash', sa.Text(), nullable=True),
    sa.Column('avatar_seed', sa.String(length=32), nullable=False),
    sa.Column('team_id', sa.UUID(), nullable=True),
    sa.Column('rank', sa.String(length=20), server_default='bronze', nullable=False),
    sa.Column('total_points', sa.Float(), server_default='0', nullable=False),
    sa.Column('total_reps', sa.Integer(), server_default='0', nullable=False),
    sa.Column('total_sessions', sa.Integer(), server_default='0', nullable=False),
    sa.Column('best_session_points', sa.Float(), server_default='0', nullable=False),
    sa.Column('best_quality', sa.Float(), server_default='0', nullable=False),
    sa.Column('current_streak', sa.Integer(), server_default='0', nullable=False),
    sa.Column('longest_streak', sa.Integer(), server_default='0', nullable=False),
    sa.Column('last_active_date', sa.Date(), nullable=True),
    sa.Column('f3_user_id', sa.UUID(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['f3_user_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['team_id'], ['league_teams.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('nickname', 'team_id', name='uq_nickname_per_team')
    )
    op.create_table('daily_logs',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('player_id', sa.UUID(), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('sessions_today', sa.Integer(), server_default='0', nullable=False),
    sa.Column('reps_today', sa.Integer(), server_default='0', nullable=False),
    sa.Column('points_today', sa.Float(), server_default='0', nullable=False),
    sa.ForeignKeyConstraint(['player_id'], ['league_players.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('player_id', 'date', name='uq_daily_log_player_date')
    )
    op.create_table('league_sessions',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('player_id', sa.UUID(), nullable=False),
    sa.Column('team_id', sa.UUID(), nullable=True),
    sa.Column('session_id', sa.UUID(), nullable=False),
    sa.Column('mode', sa.String(length=20), server_default='personal', nullable=False),
    sa.Column('reps_counted', sa.Integer(), server_default='0', nullable=False),
    sa.Column('reps_total', sa.Integer(), server_default='0', nullable=False),
    sa.Column('avg_quality', sa.Float(), server_default='0', nullable=False),
    sa.Column('points_earned', sa.Float(), server_default='0', nullable=False),
    sa.Column('duration_sec', sa.Integer(), server_default='30', nullable=False),
    sa.Column('max_combo', sa.Integer(), server_default='0', nullable=False),
    sa.Column('perfect_reps', sa.Integer(), server_default='0', nullable=False),
    sa.Column('capped', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['player_id'], ['league_players.id'], ),
    sa.ForeignKeyConstraint(['session_id'], ['sessions.id'], ),
    sa.ForeignKeyConstraint(['team_id'], ['league_teams.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_league_sessions_player_created', 'league_sessions', ['player_id', 'created_at'], unique=False)
    op.create_index('ix_league_sessions_team_created', 'league_sessions', ['team_id', 'created_at'], unique=False)
    op.drop_constraint(op.f('sessions_user_id_fkey'), 'sessions', type_='foreignkey')
    op.create_foreign_key(None, 'sessions', 'users', ['user_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'sessions', type_='foreignkey')
    op.create_foreign_key(op.f('sessions_user_id_fkey'), 'sessions', 'users', ['user_id'], ['id'], ondelete='CASCADE')
    op.drop_index('ix_league_sessions_team_created', table_name='league_sessions')
    op.drop_index('ix_league_sessions_player_created', table_name='league_sessions')
    op.drop_table('league_sessions')
    op.drop_table('daily_logs')
    op.drop_table('league_players')
    op.drop_table('league_teams')
    # ### end Alembic commands ###
