"""add_database_indexes

Revision ID: 576ecf635f11
Revises: 001
Create Date: 2026-03-01 16:14:35.322187

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '576ecf635f11'
down_revision: Union[str, None] = '001'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('analysis_jobs',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('status', sa.String(length=20), server_default='pending', nullable=False),
    sa.Column('exercise_type', sa.String(length=50), server_default='squat', nullable=False),
    sa.Column('result', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('error', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_analysis_jobs_created_at', 'analysis_jobs', ['created_at'], unique=False)
    op.create_index('ix_analysis_jobs_status', 'analysis_jobs', ['status'], unique=False)
    op.create_table('drill_completions',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('drill_name', sa.String(length=200), nullable=False),
    sa.Column('exercise_type', sa.String(length=50), nullable=False),
    sa.Column('target_area', sa.String(length=100), nullable=True),
    sa.Column('completed_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_drill_completions_user_id_completed_at', 'drill_completions', ['user_id', 'completed_at'], unique=False)
    op.drop_index(op.f('ix_refresh_tokens_user_id'), table_name='refresh_tokens')
    op.create_index('ix_refresh_tokens_expires_at', 'refresh_tokens', ['expires_at'], unique=False)
    op.create_index('ix_refresh_tokens_user_id_expires_at', 'refresh_tokens', ['user_id', 'expires_at'], unique=False)
    op.add_column('reps', sa.Column('eccentric_ms', sa.Integer(), nullable=True))
    op.add_column('reps', sa.Column('pause_ms', sa.Integer(), nullable=True))
    op.add_column('reps', sa.Column('concentric_ms', sa.Integer(), nullable=True))
    op.drop_index(op.f('ix_reps_set_id'), table_name='reps')
    op.create_index('ix_reps_set_id_rep_number', 'reps', ['set_id', 'rep_number'], unique=False)
    op.drop_index(op.f('ix_sessions_user_id'), table_name='sessions')
    op.create_index('ix_sessions_user_id_created_at', 'sessions', ['user_id', 'created_at'], unique=False)
    # Keep the existing foreign key with CASCADE — no change needed.
    # op.drop_constraint(op.f('sessions_user_id_fkey'), 'sessions', type_='foreignkey')
    # op.create_foreign_key(None, 'sessions', 'users', ['user_id'], ['id'], ondelete='CASCADE')
    op.drop_index(op.f('ix_sets_session_id'), table_name='sets')
    op.create_index('ix_sets_session_id_set_number', 'sets', ['session_id', 'set_number'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_sets_session_id_set_number', table_name='sets')
    op.create_index(op.f('ix_sets_session_id'), 'sets', ['session_id'], unique=False)
    # Foreign key was not changed in upgrade, so nothing to revert.
    # op.drop_constraint(None, 'sessions', type_='foreignkey')
    # op.create_foreign_key(op.f('sessions_user_id_fkey'), 'sessions', 'users', ['user_id'], ['id'], ondelete='CASCADE')
    op.drop_index('ix_sessions_user_id_created_at', table_name='sessions')
    op.create_index(op.f('ix_sessions_user_id'), 'sessions', ['user_id'], unique=False)
    op.drop_index('ix_reps_set_id_rep_number', table_name='reps')
    op.create_index(op.f('ix_reps_set_id'), 'reps', ['set_id'], unique=False)
    op.drop_column('reps', 'concentric_ms')
    op.drop_column('reps', 'pause_ms')
    op.drop_column('reps', 'eccentric_ms')
    op.drop_index('ix_refresh_tokens_user_id_expires_at', table_name='refresh_tokens')
    op.drop_index('ix_refresh_tokens_expires_at', table_name='refresh_tokens')
    op.create_index(op.f('ix_refresh_tokens_user_id'), 'refresh_tokens', ['user_id'], unique=False)
    op.drop_index('ix_drill_completions_user_id_completed_at', table_name='drill_completions')
    op.drop_table('drill_completions')
    op.drop_index('ix_analysis_jobs_status', table_name='analysis_jobs')
    op.drop_index('ix_analysis_jobs_created_at', table_name='analysis_jobs')
    op.drop_table('analysis_jobs')
    # ### end Alembic commands ###
